### ISSUE TITLE
Rendering artifacts with Chrome for Android

### ISSUE THREAD

**Issue by jonnenauha** [Polymer/paper-spinner#12]
Can be observed in the polymer demo page https://www.polymer-project.org/components/paper-elements/demo.html#paper-spinner

My user agen is `Mozilla/5.0 (Linux; Android 4.4.4; GT-I9300 Build/KTU84Q) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.93 Mobile Safari/537.36` and phone is Samsung Galaxy 3 (if that matters). I tried Chrome for Android beta (40) as well, looks exactly the same.

My sites other CSS animations/transitions work fine on mobile, havent tried other browsers yet.

![screenshot_2015-01-06-06-56-51](https://cloud.githubusercontent.com/assets/157519/5624611/c8a225fa-9571-11e4-8d14-dd46dfe47c5b.png)

**Comment by jonnenauha** [comment]
Looks like some kind of memory trashing. The image is not the same all the time, it changes randomly after each complete spin.

Is this a chrome bug or something you could fix? Maybe fallback to some other technique on mobile?

**Comment by jonnenauha** [comment]
Oh also I'm using the latest Polymer release. Did not try head yet, seems you have made some commits since.

```{
  name: 'paper-spinner',
  private: true,
  dependencies: {
    polymer: 'Polymer/polymer#^0.5.0',
    webcomponentsjs: 'Polymer/webcomponentsjs#^0.5.0'
  },
  version: '0.5.2',
  homepage: 'https://github.com/polymer/paper-spinner'
}```

**Comment by jonnenauha** [comment]
Ok, tried head. Still happens. Now I saw a gmail icon for one spin there, so definately some rendering mem issue :) I'm starting to get a feeling that this is not an issue in your lib but my device (seems to have plenty of free memory) or chrome.

Maybe if you or someone else can verify that some mobile device with latest Chrome works and close this. Thanks.

**Comment by keanulee** [comment]
Definitely seems like a platform/phone issue - I just tried it on my Moto X (with Android 5 and latest Chrome) and didn't see this.

**Comment by jonnenauha** [comment]
Thanks for checking
