### ISSUE TITLE
Using paper-spinner when loading application while <body unresolved>

### ISSUE THREAD

**Issue by kbwatts** [Polymer/paper-spinner#13]
The paper spinner works perfectly when polymer has already been loaded and the browser is then loading something else, but what about prior to load completion of the whole application?

While `<body>` is `unresolved`, the user has no way of seeing the paper-spinner in its existing form because it depends on polymer being already loaded.

A way around this is to set `<body>` to `resolved` and place a custom loading animation underneath, then set individual components to `unresolved`, but I suppose this isn't ideal.

Is there a better option aside from creating our own version of paper-spinner svg/gif files (or at least a backup resource of these types of files to use if there is no better workaround - see http://codepen.io/jczimm/pen/vEBpoL)? Going from the material design guidelines it seems better present users with the same loading experience throughout the whole application rather than changing it.

**Comment by keanulee** [comment]
At this point, I would consider copying the HTML/CSS from the implementation of <paper-spinner> and place it directly in the page (i.e. outside of a Polymer element). The code example you provided animates  slower CSS properties (e.g. `stroke-dashoffset`), so it might not run smoothly when your application is loading. For more details, see https://blog.keanulee.com/2014/10/20/the-tale-of-three-spinners.html.

When Polymer 0.8 is released, it will load much faster than the current version, so this workaround will probably not be needed then.

**Comment by kbwatts** [comment]
Sounds reasonable to me - thanks for your insight :+1:
