### ISSUE TITLE
Strange artifacts in Chrome 39 on Ubuntu 14.04

### ISSUE THREAD

**Issue by 0x24a537r9** [Polymer/paper-spinner#9]
I'm seeing a lot of strange artifacts in Chrome with mysterious lines and dots appearing around the spinner. Most prominent are the lines through the middle, but you can also see a green dot in the second one, which are common but somewhat hard to capture with static screenshots.

![screenshot from 2014-11-19 19 38 42](https://cloud.githubusercontent.com/assets/3403450/5119276/bd9d08c8-7023-11e4-9412-f6a45d13cb25.png)

![screenshot from 2014-11-19 19 40 23](https://cloud.githubusercontent.com/assets/3403450/5119288/f259288a-7023-11e4-9f84-7ed597d14068.png)

**Comment by jklein24** [comment]
I'm still seeing this with the 0.99 workaround, just to a lesser degree. See the following screenshot:

![spinner](https://cloud.githubusercontent.com/assets/1393755/5621411/0943184a-94ea-11e4-9163-4586e00c6451.png)

It's much easier to see while the spinner is moving, but you'll notice that the edges of the stroke are a bit fuzzy and have some artifacts still. Is there anything else we can do in the mean time?

**Comment by keanulee** [comment]
I think this is as close as we can get to spec currently (with HTML/CSS) given the platform. With that said, I would keep an eye on the Chromium bug mentioned above to see if anything progresses there.
